AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: aws-infrastructure

Resources:
  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers
      Handler: authorizer.authorizerHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Function used to authorize users to use API
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: accountAuthorizationKey
      Environment:
        Variables:
          TABLE_NAME: prod
          KEY_PARAMETER_NAME: accountAuthorizationKey
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - authorizer.ts

  AuthenticateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers
      Handler: authenticate.authenticateHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Function user to log users in
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: accountAuthorizationKey
      Environment:
        Variables:
          TABLE_NAME: prod
          KEY_PARAMETER_NAME: accountAuthorizationKey
      Events:
        Api:
          Type: Api
          Properties:
            Path: /login
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - authenticate.ts

  DevTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: dev
      AttributeDefinitions:
        - AttributeName: "recordType"
          AttributeType: "S"
        - AttributeName: "recordUniqueInformation"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "recordType"
          KeyType: "HASH"
        - AttributeName: "recordUniqueInformation"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"

  ProdTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: prod
      AttributeDefinitions:
        - AttributeName: "recordType"
          AttributeType: "S"
        - AttributeName: "recordUniqueInformation"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "recordType"
          KeyType: "HASH"
        - AttributeName: "recordUniqueInformation"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DevEnvTable:
    Description: "DynamoDB dev table name"
    Value: !GetAtt DevTable.Arn
  # ProdEnvTable:
  #   Description: "DynamoDB prod table name"
  #   Value: !GetAtt ProdTable.Arn
